import { ThemeProvider } from '@/contexts/Theme/Theme';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Experimental - Emre Koc',
    description: 'Generated by create next app',
    openGraph: {
        description: 'Just some experimental digital artwork',
        images: [
            {
                height: 630,
                width: 1200,
                url: 'https://experimental.emroni.com/assets/share.png',
            },
        ],
        siteName: 'Experimental',
        title: 'Experimental',
        type: 'website',
        url: 'https://experimental.emroni.com',
    },
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {

    return <html lang="en">
        <body>
            <ThemeProvider>
                {children}
            </ThemeProvider>
        </body>
    </html>;

}
